20000 CONSTANT M_ATTESA \DEVE TENERE IL GPIO DATA IN USCITA BASSA PER ALMENO 18 MS, DOPO DEVE RIPORTARE IL GPIO IN INGRESSO
160 CONSTANT S_ATTESA

\COMANDO PER COMUNICARE AL SENSORE CHE IL MICROCONTROLLORE E' PRONTO A RICEVERE I DATI
\ ( STANZA -- )
: START DUP THERMOS SWAP AREAD DUP DUP DUP CLRGPIO  001  ABILPIN  CLRGPIO M_ATTESA DELAY 000 ABILPIN ;


\COMANDO PER ATTENDERE CHE IL SENSORE INIZI A COMUNICARE
\ ( -- )
: WAIT S_ATTESA DELAY ;

